---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-13.04
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
- name: precise64
  driver_config:
    box: precise64
    box_url: http://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-vagrant-amd64-disk1.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: repository
  run_list:
  - recipe[minitest-handler]
  - recipe[newrelic::repository]

- name: server-monitor
  run_list:
  - recipe[minitest-handler]
  - recipe[newrelic::repository]
  - recipe[newrelic::server-monitor]
  attributes:
    newrelic:
      server_monitoring:
        license: 'TESTKEY_SERVER_MONITOR'

- name: php-agent
  run_list:
  - recipe[minitest-handler]
  - recipe[apache2]
  - recipe[newrelic::repository]
  - recipe[newrelic::php-agent]
  attributes:
    newrelic:
      application_monitoring:
        license: 'TESTKEY_PHP_AGENT'

- name: plugin-agent
  run_list:
  - recipe[minitest-handler]
  - recipe[newrelic::plugin-agent-default]
  attributes:
    newrelic:
      application_monitoring:
        license: 'TESTKEY_PLUGIN_AGENT'
