---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-13.04
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box


suites:
- name: plugin-agent
  run_list:
  - recipe[minitest-handler]
  - recipe[newrelic::plugin-agent-default]
  attributes:
    newrelic:
      application_monitoring:
        license: 'TESTKEY_PLUGIN_AGENT'
