---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    driver_config:
        box: opscode-ubuntu-12.04
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
#  - name: ubuntu-13.04
#    driver_config:
#      box: opscode-ubuntu-13.04
#      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
#  - name: centos-6.3
#    driver_config:
#        box: opscode-centos-6.3
#        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.3_provisionerless.box
  - name: centos-6.4
    driver_config:
        box: opscode-centos-6.4
        box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[newrelic::default]
    attributes:
      newrelic:
        license: '0000ffff0000ffff0000ffff0000ffff0000ffff'
        server_monitor_agent:
          service_notify_action: nothing
          service_actions:
            - nothing
#        server_monitor_agent:
#          service_notify_action: nothing
#          service_actions:
#            - nothing
#  - name: dotnet_agent
#    run_list:
#      - recipe[newrelic::dotnet_agent]
#  - name: java_agent
#    run_list:
#      - recipe[newrelic::java_agent]
#  - name: nodejs_agent
#    run_list:
#      - recipe[newrelic::nodejs_agent]
#  - name: php_agent
#    run_list:
#      - recipe[newrelic::php_agent]
#  - name: python_agent
#    run_list:
#      - recipe[newrelic::python_agent]
#  - name: repository
#    run_list:
#      - recipe[newrelic::repository]
#  - name: ruby_agent
#    run_list:
#      - recipe[newrelic::ruby_agent]
#  - name: server_monitor_agent
#    run_list:
#      - recipe[newrelic::server_monitor_agent]
#    attributes:
#      newrelic:
#        server_monitor_agent:
#          service_notify_action: nothing
#          service_actions:
#            - nothing
