---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
    attributes:
      newrelic:
        php_agent:
          web_server:
            service_name: apache2
          php_config: '/etc/php5/conf.d/newrelic.ini'
          java_agent:
            install_dir: '/opt/newrelic/java'

  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
    attributes:
      newrelic:
        php5enmode: = true
        php_agent:
          web_server:
            service_name: apache2
          php_config: '/etc/php5/mods-available/newrelic.ini'
          java_agent:
            install_dir: '/opt/newrelic/java'

  - name: centos-6.6
    attributes:
      newrelic:
        php_agent:
          web_server:
            service_name: httpd
          php_config: '/etc/php.d/newrelic.ini'
          java_agent:
            install_dir: '/opt/newrelic/java'

suites:
  - name: default
    run_list:
      - recipe[newrelic::default]
    attributes:
      newrelic:
        license: '0000ffff0000ffff0000ffff0000ffff0000ffff'
        server_monitor_agent:
          service_notify_action: nothing
          service_actions:
            - nothing
  - name: php-agent
    run_list: "recipe[newrelic_lwrp_test::agent_php]"
    attributes:
      newrelic:
        license: '0000ffff0000ffff0000ffff0000ffff0000ffff'
  - name: server-monitor
    run_list: "recipe[newrelic_lwrp_test::server_monitor]"
    attributes:
      newrelic:
        license: '0000ffff0000ffff0000ffff0000ffff0000ffff'
  - name: java-agent
    run_list: "recipe[newrelic_lwrp_test::agent_java]"
    attributes: 
      newrelic: 
        license: 0000ffff0000ffff0000ffff0000ffff0000ffff
    run_list: "recipe[newrelic_lwrp_test::agent_python]"
  - name: python-agent-recipe
    run_list: "recipe[newrelic_lwrp_test::agent_python_recipe]"
    attributes:
      newrelic:
        license: '0000ffff0000ffff0000ffff0000ffff0000ffff'
  - name: nodejs-agent
    run_list: "recipe[newrelic_lwrp_test::agent_nodejs]"
    attributes:
      newrelic:
        license: '0000ffff0000ffff0000ffff0000ffff0000ffff'
  - name: nodejs-agent-recipe
    run_list: "recipe[newrelic_lwrp_test::agent_nodejs_recipe]"
    attributes:
      newrelic:
        license: '0000ffff0000ffff0000ffff0000ffff0000ffff'
