require 'spec_helper'

install_dir = '/opt/newrelic/java'
describe file(install_dir) do
  it { should be_directory }
  it { should be_owned_by 'newrelic' }
  it { should be_grouped_into 'newrelic' }
end

describe file("#{install_dir}/newrelic.jar") do
  it { should be_file }
  it { should be_owned_by 'newrelic' }
  it { should be_grouped_into 'newrelic' }
  it { should be_mode 644 }
end

describe file("#{install_dir}/newrelic.yml") do
  it { should be_file }
  it { should be_owned_by 'newrelic' }
  it { should be_grouped_into 'newrelic' }
  it { should be_mode 644 }
  its(:content) { should match '# Generated by Chef' }
end
